name: Emage
version: ${project.version}
main: net.edithymaster.emage.EmagePlugin
description: A Minecraft plugin that displays images and GIFs on item frames.
api-version: '1.18'
authors: [EdithyMaster]
depend:
  - packetevents

commands:
  emage:
    description: Apply a static image or GIF to Item Frames
    permission: emage.use

permissions:
  emage.use:
    default: true
  emage.admin:
    default: op